import {
  CodePlugin,
  CodeblockPlugin,
  CommonPlugin,
  FilePlugin,
  HRPlugin,
  ImagePlugin,
  Kernel,
  LinkHighlightPlugin,
  LinkPlugin,
  ListPlugin,
  MathPlugin,
  MentionPlugin,
  TablePlugin,
} from '@lobehub/editor';
import { $createParagraphNode, $createTextNode, $getRoot } from 'lexical';
import { describe, expect, it, vi } from 'vitest';

import Editor from '@/editor-kernel';

import { MarkdownPlugin } from '../../plugin';
import { GET_MARKDOWN_SELECTION_COMMAND } from '../index';

const json = {
  root: {
    children: [
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'Welcome to the Lobe Editor Demo!',
            type: 'text',
            version: 1,
            id: '2',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'heading',
        version: 1,
        tag: 'h1',
        id: '1',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: "In case you were wondering what the black box at the bottom is – it's the debug view, showing the current state of the editor. You can disable it by pressing on the settings control in the bottom-left of your screen and toggling the debug view setting.",
            type: 'text',
            version: 1,
            id: '4',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'quote',
        version: 1,
        id: '3',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: 'The playground is a demo environment built with ',
            type: 'text',
            version: 1,
            id: '6',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '﻿',
                type: 'cursor',
                version: 1,
                id: '8',
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '﻿',
                type: 'cursor',
                version: 1,
                id: '9',
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '﻿',
                type: 'cursor',
                version: 1,
                id: '10',
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '﻿',
                type: 'cursor',
                version: 1,
                id: '11',
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '@lobehub/editor',
                type: 'text',
                version: 1,
                id: '12',
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'codeInline',
            version: 1,
            id: '7',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: '﻿',
            type: 'cursor',
            version: 1,
            id: '13',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: '. Try typing in ',
            type: 'text',
            version: 1,
            id: '14',
          },
          {
            detail: 0,
            format: 1,
            mode: 'normal',
            style: '',
            text: 'some text',
            type: 'text',
            version: 1,
            id: '15',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: ' with ',
            type: 'text',
            version: 1,
            id: '16',
          },
          {
            detail: 0,
            format: 2,
            mode: 'normal',
            style: '',
            text: 'different formats',
            type: 'text',
            version: 1,
            id: '17',
          },
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: '.',
            type: 'text',
            version: 1,
            id: '18',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: '5',
      },
      {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Visit the ',
                type: 'text',
                version: 1,
                id: '21',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Lobe Editor website',
                    type: 'text',
                    version: 1,
                    id: '23',
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'link',
                version: 1,
                rel: 'noreferrer',
                target: null,
                title: null,
                url: 'https://editor.lobehub.com',
                id: '22',
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' for documentation and more information.',
                type: 'text',
                version: 1,
                id: '24',
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 1,
            id: '20',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Check out the code on our ',
                type: 'text',
                version: 1,
                id: '26',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'GitHub repository',
                    type: 'text',
                    version: 1,
                    id: '28',
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'link',
                version: 1,
                rel: null,
                target: null,
                title: 'https://github.com/lobehub/lobe-editor',
                url: 'https://github.com/lobehub/lobe-editor',
                id: '27',
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: '.',
                type: 'text',
                version: 1,
                id: '29',
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 2,
            id: '25',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Playground code ',
                type: 'text',
                version: 1,
                id: '31',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Playground code',
                    type: 'text',
                    version: 1,
                    id: '33',
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'link',
                version: 1,
                rel: 'noreferrer',
                target: null,
                title: null,
                url: 'https://github.com/lobehub/lobe-editor/blob/master/src/react/Editor/demos/index.tsx',
                id: '32',
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' can be found here.',
                type: 'text',
                version: 1,
                id: '34',
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 3,
            id: '30',
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Join our ',
                type: 'text',
                version: 1,
                id: '36',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Discover Server',
                    type: 'text',
                    version: 1,
                    id: '38',
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'link',
                version: 1,
                rel: null,
                target: null,
                title: 'https://discord.gg/AYFPHvv2jT',
                url: 'https://discord.gg/AYFPHvv2jT',
                id: '37',
              },
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: ' and chat with the team.',
                type: 'text',
                version: 1,
                id: '39',
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'listitem',
            version: 1,
            value: 4,
            id: '35',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'list',
        version: 1,
        listType: 'bullet',
        start: 1,
        tag: 'ul',
        id: '19',
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: 'normal',
            style: '',
            text: "Lastly, we're constantly adding cool new features to this playground. So make sure you check back here when you next get a chance 🙂.",
            type: 'text',
            version: 1,
            id: '41',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: '40',
      },
      {
        type: 'code',
        version: 1,
        code: "import { Editor } from '@lobehub/editor';",
        codeTheme: 'default',
        language: 'typescript',
        options: {
          indentWithTabs: false,
          lineNumbers: false,
          tabSize: 2,
        },
        id: '42',
      },
      {
        children: [],
        direction: null,
        format: '',
        indent: 0,
        type: 'paragraph',
        version: 1,
        textFormat: 0,
        textStyle: '',
        id: '43',
      },
    ],
    direction: 'ltr',
    format: '',
    indent: 0,
    type: 'root',
    version: 1,
    id: 'root',
  },
};

describe('Markdown Commands', () => {
  describe('GET_MARKDOWN_SELECTION_COMMAND', () => {
    it('should get markdown selection with correct line numbers', async () => {
      const editor = Editor.createEditor().registerPlugins([
        CodePlugin,
        CodeblockPlugin,
        CommonPlugin,
        FilePlugin,
        HRPlugin,
        ImagePlugin,
        LinkPlugin,
        LinkHighlightPlugin,
        ListPlugin,
        MarkdownPlugin,
        MathPlugin,
        MentionPlugin,
        TablePlugin,
      ]);
      editor.initNodeEditor();
      // Set up editor with multi-line content
      editor.setDocument('json', json, { keepId: true });
      editor.setSelection({
        endNodeId: '28',
        endOffset: 6,
        startNodeId: '6',
        startOffset: 33,
        type: 'range',
      });
      const ret = await new Promise((resolve) => {
        editor.dispatchCommand(GET_MARKDOWN_SELECTION_COMMAND, {
          onResult: (startLine: number, endLine: number) => {
            resolve({ startLine, endLine });
          },
        });
      });
      expect(ret).toEqual({ startLine: 5, endLine: 8 });
    });
  });
});
