// @vitest-environment jsdom
import { beforeEach, describe, expect, it, vi } from 'vitest';
import {
  $createRangeSelection,
  $getRoot,
  $isElementNode,
  $isTextNode,
  $setSelection,
  KEY_TAB_COMMAND,
} from 'lexical';

import Editor from '@/editor-kernel';
import { CommonPlugin } from '@/plugins/common';
import { MarkdownPlugin } from '@/plugins/markdown';
import {
  $getNodeProperties,
  PropertiesPlugin,
  markSerializedNodesAsAIGenerated,
} from '@/plugins/properties';

import { AutoCompletePlugin } from '../index';

const flush = async (count = 1) => {
  for (let index = 0; index < count; index++) {
    await new Promise<void>((resolve) => setTimeout(resolve, 0));
  }
};

describe('AutoComplete AI provenance', () => {
  beforeEach(() => {
    vi.useRealTimers();
  });

  it('injects provenance before inserting the accepted Tab suggestion', async () => {
    const accepted = vi.fn();
    const kernel = Editor.createEditor().registerPlugins([
      CommonPlugin,
      MarkdownPlugin,
      PropertiesPlugin,
      [
        AutoCompletePlugin,
        {
          delay: 0,
          model: 'test-model',
          onAutoComplete: async () => 'generated by ai',
          onSuggestionAccepted: accepted,
          provider: 'test-provider',
        },
      ],
    ]);
    const lexical = kernel.setRootElement(document.createElement('div'));
    kernel.setDocument('markdown', 'Existing');

    lexical.update(() => {
      const paragraph = $getRoot().getFirstChild();
      if (!$isElementNode(paragraph)) throw new Error('Expected paragraph');
      const text = paragraph.getFirstChild();
      if (!$isTextNode(text)) throw new Error('Expected text');
      const selection = $createRangeSelection();
      selection.anchor.set(text.getKey(), text.getTextContentSize(), 'text');
      selection.focus.set(text.getKey(), text.getTextContentSize(), 'text');
      $setSelection(selection);
    });

    await flush(4);
    lexical.dispatchCommand(KEY_TAB_COMMAND, null as unknown as KeyboardEvent);
    await flush(4);

    expect(accepted).toHaveBeenCalledWith(
      expect.objectContaining({ acceptedText: 'generated by ai' }),
    );
    const generatedNodes: Array<{ text: string; provenance?: unknown }> = [];
    lexical.getEditorState().read(() => {
      for (const node of $getRoot().getAllTextNodes()) {
        const properties = $getNodeProperties(node);
        generatedNodes.push({ provenance: properties.provenance, text: node.getTextContent() });
      }
    });
    expect(generatedNodes).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          provenance: expect.objectContaining({
            generationId: expect.stringMatching(/^acp/),
            model: 'test-model',
            provider: 'test-provider',
            source: 'ai',
          }),
          text: 'generated by ai',
        }),
      ]),
    );
    kernel.destroy();
  });

  it('preserves existing serialized state while adding provenance to every generated node', () => {
    const root: any = {
      children: [
        {
          $: { properties: { custom: 'keep' } },
          children: [{ text: 'Generated', type: 'text', version: 1 }],
          type: 'paragraph',
          version: 1,
        },
      ],
    };

    markSerializedNodesAsAIGenerated(root, {
      generationId: 'generation-1',
      provider: 'test-provider',
    });

    expect(root.children[0].$).toMatchObject({
      properties: {
        custom: 'keep',
        provenance: expect.objectContaining({ source: 'ai' }),
      },
    });
    expect(root.children[0].children[0].$).toMatchObject({
      properties: {
        provenance: expect.objectContaining({ generationId: 'generation-1' }),
      },
    });
  });
});
