name: Issue Check Inactive

on:
  schedule:
    - cron: '0 0 */15 * *'

permissions:
  contents: read

jobs:
  issue-check-inactive:
    permissions:
      issues: write # for issue automation
      pull-requests: write # for issue automation
    runs-on: ubuntu-latest
    steps:
      - name: check-inactive
        run: echo "Temporarily disabled issue automation."
